apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: testing
  annotations:
      kubernetes.io/change-cause: vuelvo a 1 replica
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: nginx:alpine
        resources:
          requests:
            memory: "5Mi"
            cpu: "5m"
          limits:
            memory: "10Mi"
            cpu: "20m"
        ports:
        - containerPort: 80
