apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: testing
  annotations:
      kubernetes.io/change-cause: cambio de imagen a traefik/whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: traefik/whoami
        resources:
          requests:
            memory: "50Mi"
            cpu: "100m"
          limits:
            memory: "100Mi"
            cpu: "200m"
        ports:
        - containerPort: 80
