apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: testing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: nginx:alpine
        resources:
          limits:
            memory: "12Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
