apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: nginx.pi3 
    http:
      paths:
      - backend:
          serviceName: app-service
          servicePort: 80
  